### ISSUE TITLE
Fix issue with imports

### ISSUE THREAD

**Issue by fareskalaboud** [fareskalaboud/pybugger2#1]
For some reason, I can't get the import of the module `pybugger2.py` to work.

Basically, in order to run any method at the moment, you have to write 

`pybugger.pybugger2.methodname()`

Whereas it really should be 

`pybugger2.methodname()`

The issue is that we start with an `import pybugger`, which works. However, if we try `import pybugger.pybugger2`, it says it can't find the module.

**Comment by kalbhor** [comment]
I'd like to take this up.

**Comment by kalbhor** [comment]
Fixed :) 

I have tried and tested it.

**Comment by fareskalaboud** [comment]
@kalbhor brilliant! I'm going to merge and then push it onto pip.
